"""
Predefined register maps for common cold storage controllers.

These are seeded into the register_maps table on first run.
Each map defines the Modbus registers or BACnet objects for a specific
controller model, so the platform knows how to read data from them
without manual configuration.

Register addresses are based on publicly available documentation
and field experience with these controller families.
"""

REGISTER_MAP_SEEDS = [
    # ── Emerson E2 Controller (Modbus TCP) ──────────────
    # The #1 controller in US mid-market cold storage.
    # E2 exposes ~200+ registers. This covers the most critical ones
    # for cold storage monitoring.
    {
        "name": "emerson_e2_v4",
        "protocol": "modbus_tcp",
        "manufacturer": "Emerson",
        "model": "E2 / E3",
        "description": (
            "Emerson E2/E3 controller — suction group, condenser, "
            "and circuit/case controller registers. Covers rack systems, "
            "parallels, walk-in coolers/freezers. The most deployed "
            "controller in US cold storage."
        ),
        "version": "4.0",
        "registers": {
            "registers": [
                # ── Suction Group (Rack/Compressor) ──
                {
                    "address": 40001,
                    "name": "suction_temp",
                    "description": "Suction line temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40002,
                    "name": "suction_pressure",
                    "description": "Suction pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40003,
                    "name": "discharge_temp",
                    "description": "Discharge line temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40004,
                    "name": "discharge_pressure",
                    "description": "Discharge / head pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40005,
                    "name": "oil_pressure",
                    "description": "Oil pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40010,
                    "name": "suction_setpoint",
                    "description": "Suction pressure setpoint",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": 0,
                    "max_value": 100,
                    "safety_lock": True,
                },
                {
                    "address": 40011,
                    "name": "compressor_stage",
                    "description": "Current compressor staging (% capacity)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40012,
                    "name": "compressor_runtime",
                    "description": "Compressor runtime hours",
                    "data_type": "uint32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "hours",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Condenser ──
                {
                    "address": 40020,
                    "name": "condenser_temp",
                    "description": "Condenser saturation temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40021,
                    "name": "condenser_pressure",
                    "description": "Condenser / head pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40022,
                    "name": "condenser_fan_speed",
                    "description": "Condenser fan speed (%)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40023,
                    "name": "condenser_setpoint",
                    "description": "Condenser pressure setpoint",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": 50,
                    "max_value": 300,
                    "safety_lock": True,
                },
                # ── Circuit / Case Controller ──
                {
                    "address": 40100,
                    "name": "zone_temp",
                    "description": "Zone / case air temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40101,
                    "name": "zone_setpoint",
                    "description": "Zone temperature setpoint",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": -40,
                    "max_value": 60,
                    "safety_lock": True,
                },
                {
                    "address": 40102,
                    "name": "evap_coil_temp",
                    "description": "Evaporator coil temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40103,
                    "name": "defrost_state",
                    "description": "Defrost state (0=off, 1=active, 2=draining)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40104,
                    "name": "door_state",
                    "description": "Door switch state (0=closed, 1=open)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40105,
                    "name": "superheat",
                    "description": "Superheat (evaporator)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Power / Energy ──
                {
                    "address": 40200,
                    "name": "total_power",
                    "description": "Total system power consumption",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "kW",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40202,
                    "name": "total_energy",
                    "description": "Total energy consumption (cumulative)",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "kWh",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
            ]
        },
    },

    # ── Danfoss AK-PC 781 (Modbus TCP) ─────────────────
    # Pack controller — common in European cold storage and
    # increasingly in US facilities.
    {
        "name": "danfoss_ak_pc_781",
        "protocol": "modbus_tcp",
        "manufacturer": "Danfoss",
        "model": "AK-PC 781",
        "description": (
            "Danfoss AK-PC 781 pack controller — manages compressor "
            "packs, condensers, and has built-in energy optimization. "
            "Common in ammonia and CO2 systems."
        ),
        "version": "1.0",
        "registers": {
            "registers": [
                {
                    "address": 100,
                    "name": "suction_pressure",
                    "description": "Suction pressure (Po)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "bar",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 101,
                    "name": "suction_temp",
                    "description": "Suction gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 102,
                    "name": "discharge_pressure",
                    "description": "Discharge pressure (Pc)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "bar",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 103,
                    "name": "discharge_temp",
                    "description": "Discharge gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 110,
                    "name": "suction_setpoint",
                    "description": "Suction pressure reference (Po ref)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "bar",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": -1.0,
                    "max_value": 15.0,
                    "safety_lock": True,
                },
                {
                    "address": 120,
                    "name": "compressor_capacity",
                    "description": "Current compressor capacity (%)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 130,
                    "name": "condenser_pressure",
                    "description": "Condenser pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "bar",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 131,
                    "name": "condenser_fan_speed",
                    "description": "Condenser fan speed",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 140,
                    "name": "outdoor_temp",
                    "description": "Outdoor / ambient temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 200,
                    "name": "alarm_status",
                    "description": "Alarm status word (bitmask)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
            ]
        },
    },

    # ── Allen-Bradley CompactLogix (Modbus TCP Bridge) ──
    # AB PLCs are everywhere in industrial ammonia refrigeration.
    # They don't speak Modbus natively — requires a bridge module
    # (ProSoft MVI69-MCM, Anybus, etc.) or EtherNet/IP adapter.
    # This map is for the Modbus bridge path.
    {
        "name": "ab_compactlogix_ammonia",
        "protocol": "modbus_tcp",
        "manufacturer": "Allen-Bradley / Rockwell",
        "model": "CompactLogix (via Modbus bridge)",
        "description": (
            "Allen-Bradley CompactLogix PLC controlling industrial "
            "ammonia refrigeration. Accessed via Modbus TCP bridge module. "
            "Register addresses depend on the PLC program — these are "
            "typical for ammonia engine room applications."
        ),
        "version": "1.0",
        "registers": {
            "registers": [
                {
                    "address": 0,
                    "name": "suction_pressure",
                    "description": "Suction pressure (low side)",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 2,
                    "name": "discharge_pressure",
                    "description": "Discharge pressure (high side)",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 4,
                    "name": "suction_temp",
                    "description": "Suction gas temperature",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 6,
                    "name": "discharge_temp",
                    "description": "Discharge gas temperature",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 8,
                    "name": "oil_pressure",
                    "description": "Compressor oil pressure",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 10,
                    "name": "oil_temp",
                    "description": "Oil sump temperature",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 12,
                    "name": "motor_amps",
                    "description": "Compressor motor current draw",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "amps",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 14,
                    "name": "slide_valve_position",
                    "description": "Screw compressor slide valve position",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 16,
                    "name": "liquid_level",
                    "description": "Receiver / vessel liquid level",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 18,
                    "name": "ammonia_concentration",
                    "description": "Ammonia gas detector reading (engine room)",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "ppm",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 50,
                    "name": "suction_setpoint",
                    "description": "Suction pressure setpoint",
                    "data_type": "float32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 16,
                    "min_value": 0,
                    "max_value": 60,
                    "safety_lock": True,
                },
            ]
        },
    },

    # ── BACnet/IP — Honeywell Spyder ────────────────────
    # Programmable DDC controller used as zone/AHU controller
    # in cold storage facilities with Honeywell BAS.
    {
        "name": "honeywell_spyder_bacnet",
        "protocol": "bacnet_ip",
        "manufacturer": "Honeywell",
        "model": "Spyder (PUL/PVL series)",
        "description": (
            "Honeywell Spyder programmable controller — zone-level "
            "DDC for cold rooms, AHUs, and process cooling. "
            "BACnet/IP native."
        ),
        "version": "1.0",
        "registers": {
            "objects": [
                {
                    "object_type": "analog-input",
                    "instance": 1,
                    "name": "zone_temp",
                    "description": "Zone air temperature",
                    "unit": "degF",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 2,
                    "name": "zone_humidity",
                    "description": "Zone relative humidity",
                    "unit": "percent",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 3,
                    "name": "supply_air_temp",
                    "description": "Supply air temperature",
                    "unit": "degF",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 4,
                    "name": "return_air_temp",
                    "description": "Return air temperature",
                    "unit": "degF",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-value",
                    "instance": 1,
                    "name": "zone_setpoint",
                    "description": "Zone temperature setpoint",
                    "unit": "degF",
                    "property": "present-value",
                    "access": "read_write",
                    "min_value": -40,
                    "max_value": 60,
                },
                {
                    "object_type": "analog-value",
                    "instance": 2,
                    "name": "humidity_setpoint",
                    "description": "Humidity setpoint",
                    "unit": "percent",
                    "property": "present-value",
                    "access": "read_write",
                    "min_value": 10,
                    "max_value": 95,
                },
                {
                    "object_type": "analog-output",
                    "instance": 1,
                    "name": "cooling_valve",
                    "description": "Cooling valve position",
                    "unit": "percent",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "binary-input",
                    "instance": 1,
                    "name": "door_state",
                    "description": "Door contact (0=closed, 1=open)",
                    "unit": "",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "binary-input",
                    "instance": 2,
                    "name": "defrost_active",
                    "description": "Defrost in progress",
                    "unit": "",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "binary-value",
                    "instance": 1,
                    "name": "occupancy_mode",
                    "description": "Occupied/unoccupied mode",
                    "unit": "",
                    "property": "present-value",
                    "access": "read_write",
                },
            ]
        },
    },

    # ── Danfoss AK-SM 800A (BACnet/IP) ─────────────────
    # System manager — aggregates multiple case controllers.
    {
        "name": "danfoss_ak_sm_800a_bacnet",
        "protocol": "bacnet_ip",
        "manufacturer": "Danfoss",
        "model": "AK-SM 800A",
        "description": (
            "Danfoss AK-SM 800A system manager via BACnet/IP. "
            "Exposes aggregated pack and case data from the "
            "entire Danfoss ADAP-KOOL network."
        ),
        "version": "1.0",
        "registers": {
            "objects": [
                {
                    "object_type": "analog-input",
                    "instance": 100,
                    "name": "suction_pressure",
                    "description": "Pack controller suction pressure",
                    "unit": "bar",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 101,
                    "name": "discharge_pressure",
                    "description": "Pack controller discharge pressure",
                    "unit": "bar",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 200,
                    "name": "case_temp_1",
                    "description": "Case controller 1 — air temperature",
                    "unit": "degC",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 201,
                    "name": "case_temp_2",
                    "description": "Case controller 2 — air temperature",
                    "unit": "degC",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-value",
                    "instance": 200,
                    "name": "case_setpoint_1",
                    "description": "Case controller 1 — setpoint",
                    "unit": "degC",
                    "property": "present-value",
                    "access": "read_write",
                    "min_value": -35,
                    "max_value": 15,
                },
                {
                    "object_type": "binary-input",
                    "instance": 200,
                    "name": "case_defrost_1",
                    "description": "Case controller 1 — defrost active",
                    "unit": "",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "multi-state-input",
                    "instance": 100,
                    "name": "pack_alarm_state",
                    "description": "Pack alarm state (1=normal, 2=warning, 3=alarm)",
                    "unit": "",
                    "property": "present-value",
                    "access": "read",
                },
                {
                    "object_type": "analog-input",
                    "instance": 300,
                    "name": "total_power",
                    "description": "Total system power consumption",
                    "unit": "kW",
                    "property": "present-value",
                    "access": "read",
                },
            ]
        },
    },

    # ── Bitzer IQ Module (Modbus TCP) ───────────────────
    # Compressor intelligence module — mounted directly on
    # Bitzer semi-hermetic and screw compressors.
    {
        "name": "bitzer_iq_module",
        "protocol": "modbus_tcp",
        "manufacturer": "Bitzer",
        "model": "IQ Module (CM-RC-01 / BEST)",
        "description": (
            "Bitzer IQ compressor intelligence module. Provides "
            "direct compressor diagnostics: pressures, temperatures, "
            "motor data, and protection status."
        ),
        "version": "1.0",
        "registers": {
            "registers": [
                {
                    "address": 1000,
                    "name": "suction_pressure",
                    "description": "Suction pressure (LP)",
                    "data_type": "int16",
                    "scale": 0.01,
                    "offset": 0,
                    "unit": "bar",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1001,
                    "name": "discharge_pressure",
                    "description": "Discharge pressure (HP)",
                    "data_type": "int16",
                    "scale": 0.01,
                    "offset": 0,
                    "unit": "bar",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1002,
                    "name": "suction_temp",
                    "description": "Suction gas superheat temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1003,
                    "name": "discharge_temp",
                    "description": "Discharge gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1004,
                    "name": "oil_temp",
                    "description": "Oil sump temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1010,
                    "name": "motor_current",
                    "description": "Motor current draw",
                    "data_type": "uint16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "amps",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1011,
                    "name": "motor_winding_temp",
                    "description": "Motor winding temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degC",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1020,
                    "name": "runtime_hours",
                    "description": "Compressor runtime hours",
                    "data_type": "uint32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "hours",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 1030,
                    "name": "protection_status",
                    "description": "Protection status bitmask",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 4,
                    "byte_order": "big",
                    "access": "read",
                },
            ]
        },
    },
    # ── Emerson E2 (BACnet IP) ─────────────────────
    # Same controller, BACnet interface variant.
    {
        "name": "emerson_e2_bacnet",
        "protocol": "bacnet_ip",
        "manufacturer": "Emerson",
        "model": "E2 / E3 (BACnet)",
        "description": (
            "Emerson E2/E3 controller accessed via BACnet/IP. "
            "Maps standard BACnet objects for suction group, condenser, "
            "and case controller points. Use when the E2 is on a BACnet network."
        ),
        "version": "1.0",
        "registers": {
            "protocol": "bacnet_ip",
            "device_instance_range": [1, 4194303],
            "objects": [
                {"object_type": "analog-input", "instance": 1, "name": "suction_temp", "unit": "degF", "description": "Suction line temperature"},
                {"object_type": "analog-input", "instance": 2, "name": "suction_pressure", "unit": "psig", "description": "Suction pressure"},
                {"object_type": "analog-input", "instance": 3, "name": "discharge_pressure", "unit": "psig", "description": "Discharge pressure"},
                {"object_type": "analog-input", "instance": 4, "name": "discharge_temp", "unit": "degF", "description": "Discharge temperature"},
                {"object_type": "analog-input", "instance": 10, "name": "condenser_pressure", "unit": "psig", "description": "Condenser pressure"},
                {"object_type": "analog-input", "instance": 11, "name": "ambient_temp", "unit": "degF", "description": "Outdoor ambient temperature"},
                {"object_type": "analog-input", "instance": 20, "name": "case_temp", "unit": "degF", "description": "Case/zone temperature"},
                {"object_type": "analog-value", "instance": 1, "name": "suction_setpoint", "unit": "degF", "description": "Suction setpoint", "writable": True},
                {"object_type": "analog-value", "instance": 2, "name": "condenser_setpoint", "unit": "degF", "description": "Condenser setpoint", "writable": True},
                {"object_type": "binary-input", "instance": 1, "name": "compressor_running", "description": "Compressor run status"},
                {"object_type": "binary-input", "instance": 2, "name": "defrost_active", "description": "Defrost cycle active"},
                {"object_type": "binary-value", "instance": 1, "name": "compressor_enable", "description": "Compressor enable/disable", "writable": True},
                {"object_type": "multi-state-value", "instance": 1, "name": "operating_mode", "states": ["off", "cooling", "defrost", "standby"], "description": "Controller operating mode"},
            ],
        },
    },

    # ── Danfoss AK-PC 783A (BACnet IP) ──────────────
    {
        "name": "danfoss_akpc783_bacnet",
        "protocol": "bacnet_ip",
        "manufacturer": "Danfoss",
        "model": "AK-PC 783A (BACnet)",
        "description": (
            "Danfoss AK-PC 783A pack controller for industrial refrigeration. "
            "BACnet/IP interface for compressor rack monitoring and control. "
            "Commonly used in European and large-format cold storage."
        ),
        "version": "1.0",
        "registers": {
            "protocol": "bacnet_ip",
            "device_instance_range": [1, 4194303],
            "objects": [
                {"object_type": "analog-input", "instance": 1, "name": "suction_pressure", "unit": "bar", "description": "Suction pressure (Po)"},
                {"object_type": "analog-input", "instance": 2, "name": "discharge_pressure", "unit": "bar", "description": "Discharge pressure (Pc)"},
                {"object_type": "analog-input", "instance": 3, "name": "suction_temp", "unit": "degC", "description": "Suction temperature"},
                {"object_type": "analog-input", "instance": 4, "name": "discharge_temp", "unit": "degC", "description": "Discharge temperature"},
                {"object_type": "analog-input", "instance": 5, "name": "oil_pressure", "unit": "bar", "description": "Oil pressure differential"},
                {"object_type": "analog-input", "instance": 10, "name": "power_consumption", "unit": "kW", "description": "Total power consumption"},
                {"object_type": "analog-input", "instance": 11, "name": "capacity_pct", "unit": "%", "description": "Current capacity utilization"},
                {"object_type": "analog-value", "instance": 1, "name": "suction_setpoint", "unit": "bar", "description": "Suction pressure setpoint", "writable": True},
                {"object_type": "analog-value", "instance": 2, "name": "capacity_limit", "unit": "%", "description": "Max capacity limit", "writable": True},
                {"object_type": "binary-input", "instance": 1, "name": "pack_running", "description": "Pack running status"},
                {"object_type": "binary-input", "instance": 2, "name": "high_pressure_alarm", "description": "High pressure cutout alarm"},
                {"object_type": "binary-input", "instance": 3, "name": "low_pressure_alarm", "description": "Low pressure alarm"},
                {"object_type": "binary-value", "instance": 1, "name": "pack_enable", "description": "Pack enable/disable", "writable": True},
            ],
        },
    },

    # ── Bitzer BEST (Cloud-to-Cloud API) ─────────────
    {
        "name": "bitzer_best_cloud",
        "protocol": "cloud_api",
        "manufacturer": "Bitzer",
        "model": "BEST (Cloud)",
        "description": (
            "Bitzer BEST (Bitzer Electronics Service Tool) cloud integration. "
            "Pulls compressor data from Bitzer's cloud API rather than direct on-site "
            "protocol. Requires Bitzer Digital Network credentials."
        ),
        "version": "1.0",
        "registers": {
            "protocol": "cloud_api",
            "api_base_url": "https://api.bitzer-digital.com/v1",
            "auth_method": "oauth2_client_credentials",
            "endpoints": {
                "list_compressors": {"method": "GET", "path": "/compressors"},
                "get_status": {"method": "GET", "path": "/compressors/{device_id}/status"},
                "get_operating_data": {"method": "GET", "path": "/compressors/{device_id}/operating-data"},
            },
            "field_mappings": {
                "suction_pressure": {"path": "operating_data.suction_pressure", "unit": "bar"},
                "discharge_pressure": {"path": "operating_data.discharge_pressure", "unit": "bar"},
                "discharge_temp": {"path": "operating_data.discharge_temperature", "unit": "degC"},
                "oil_temp": {"path": "operating_data.oil_temperature", "unit": "degC"},
                "motor_current": {"path": "operating_data.motor_current", "unit": "A"},
                "capacity_pct": {"path": "operating_data.capacity", "unit": "%"},
                "running_hours": {"path": "status.running_hours", "unit": "h"},
                "compressor_status": {"path": "status.operating_state"},
            },
        },
    },

    # ── Frick Quantum HD (Johnson Controls) — Modbus TCP ──
    # The dominant controller on Frick industrial screw compressors
    # (RWF, TDSH, RXF series). Ubiquitous in ammonia cold storage
    # engine rooms. Register map based on Frick Quantum HD
    # Installation Manual register tables.
    {
        "name": "frick_quantum_hd",
        "protocol": "modbus_tcp",
        "manufacturer": "Johnson Controls / Frick",
        "model": "Quantum HD (RWF / TDSH / RXF)",
        "description": (
            "Frick Quantum HD controller for industrial screw compressors "
            "(RWF, TDSH, RXF series). The most widely deployed controller "
            "in ammonia cold storage engine rooms in North America. "
            "Registers start at 40301 per Frick Quantum HD Installation "
            "Manual register tables."
        ),
        "version": "1.0",
        "registers": {
            "registers": [
                # ── Process Pressures ──
                {
                    "address": 40301,
                    "name": "suction_pressure",
                    "description": "Suction pressure (low side)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40302,
                    "name": "discharge_pressure",
                    "description": "Discharge pressure (high side)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40303,
                    "name": "oil_pressure",
                    "description": "Oil supply pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40304,
                    "name": "economizer_pressure",
                    "description": "Economizer / intermediate pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40305,
                    "name": "oil_filter_differential",
                    "description": "Oil filter differential pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Process Temperatures ──
                {
                    "address": 40310,
                    "name": "suction_temp",
                    "description": "Suction gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40311,
                    "name": "discharge_temp",
                    "description": "Discharge gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40312,
                    "name": "oil_temp",
                    "description": "Oil sump / supply temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40313,
                    "name": "bearing_temp",
                    "description": "Bearing temperature (drive-end)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Motor / Drive ──
                {
                    "address": 40320,
                    "name": "motor_amps",
                    "description": "Motor current draw",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "amps",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40321,
                    "name": "motor_kw",
                    "description": "Motor power consumption",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "kW",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40322,
                    "name": "compressor_rpm",
                    "description": "Compressor shaft speed",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "rpm",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40323,
                    "name": "vibration",
                    "description": "Compressor vibration (drive-end)",
                    "data_type": "uint16",
                    "scale": 0.01,
                    "offset": 0,
                    "unit": "in/s",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Slide Valve / Capacity ──
                {
                    "address": 40330,
                    "name": "slide_valve_position",
                    "description": "Capacity slide valve position (0–100%)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Run Hours (uint32 spans two consecutive registers) ──
                {
                    "address": 40340,
                    "name": "run_hours",
                    "description": "Compressor run hours (high word at 40340, low word at 40341)",
                    "data_type": "uint32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "hours",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Status & Faults ──
                {
                    "address": 40350,
                    "name": "compressor_status",
                    "description": "Compressor operating state (0=off, 1=running, 2=fault, 3=lockout)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40351,
                    "name": "active_fault_code",
                    "description": "Active fault / trip code (0 = no fault)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Writable Setpoints ──
                {
                    "address": 40360,
                    "name": "capacity_setpoint",
                    "description": "Capacity setpoint (% — operator demand signal)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": 0,
                    "max_value": 100,
                },
                {
                    "address": 40361,
                    "name": "suction_pressure_setpoint",
                    "description": "Suction pressure setpoint (PSI)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": 0,
                    "max_value": 150,
                    "safety_lock": True,
                },
            ]
        },
    },

    # ── GEA Omni (Grasso / CompAir) — Modbus TCP ───────
    # GEA's current-generation controller for their screw compressor
    # line. Used on Grasso SP and GEA Bock compressors in large
    # industrial refrigeration and cold storage installations.
    {
        "name": "gea_omni",
        "protocol": "modbus_tcp",
        "manufacturer": "GEA",
        "model": "Omni (Grasso SP / GEA Bock)",
        "description": (
            "GEA Omni controller for Grasso SP and GEA Bock screw "
            "compressors. Current-generation platform replacing the "
            "legacy Grasso N2000. Common in large industrial ammonia "
            "and CO2 refrigeration installations."
        ),
        "version": "1.0",
        "registers": {
            "registers": [
                # ── Process Pressures ──
                {
                    "address": 40501,
                    "name": "suction_pressure",
                    "description": "Suction pressure (low side)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40502,
                    "name": "discharge_pressure",
                    "description": "Discharge pressure (high side)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40503,
                    "name": "oil_pressure",
                    "description": "Oil supply pressure",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "psi",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Process Temperatures ──
                {
                    "address": 40510,
                    "name": "suction_temp",
                    "description": "Suction gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40511,
                    "name": "discharge_temp",
                    "description": "Discharge gas temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40512,
                    "name": "oil_temp",
                    "description": "Oil sump / supply temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40513,
                    "name": "winding_temp",
                    "description": "Motor winding temperature",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Motor / Drive ──
                {
                    "address": 40520,
                    "name": "motor_current",
                    "description": "Motor current draw",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "amps",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40521,
                    "name": "motor_power",
                    "description": "Motor power consumption",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "kW",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40522,
                    "name": "compressor_speed",
                    "description": "Compressor shaft speed",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "rpm",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Slide Valve / Volume Ratio ──
                {
                    "address": 40530,
                    "name": "slide_valve_position",
                    "description": "Capacity slide valve position (volume ratio / % capacity)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Run Hours (uint32 spans two consecutive registers) ──
                {
                    "address": 40540,
                    "name": "run_hours",
                    "description": "Compressor run hours (high word at 40540, low word at 40541)",
                    "data_type": "uint32",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "hours",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Status, Faults & Fluid Level ──
                {
                    "address": 40550,
                    "name": "compressor_status",
                    "description": "Compressor operating state (0=off, 1=running, 2=fault, 3=lockout)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40551,
                    "name": "fault_code",
                    "description": "Active fault / trip code (0 = no fault)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40552,
                    "name": "oil_level",
                    "description": "Oil separator / sump level",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Refrigerant-side Thermodynamics ──
                {
                    "address": 40560,
                    "name": "subcooling",
                    "description": "Liquid subcooling (condenser outlet)",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                {
                    "address": 40561,
                    "name": "superheat",
                    "description": "Suction superheat",
                    "data_type": "int16",
                    "scale": 0.1,
                    "offset": 0,
                    "unit": "degF",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read",
                },
                # ── Writable Setpoints ──
                {
                    "address": 40570,
                    "name": "capacity_setpoint",
                    "description": "Capacity setpoint (% — operator demand signal)",
                    "data_type": "uint16",
                    "scale": 1.0,
                    "offset": 0,
                    "unit": "percent",
                    "function_code": 3,
                    "byte_order": "big",
                    "access": "read_write",
                    "write_function_code": 6,
                    "min_value": 0,
                    "max_value": 100,
                },
            ]
        },
    },

    # ── Copeland Scroll Digital (Cloud API) ──────────
    {
        "name": "copeland_scroll_cloud",
        "protocol": "cloud_api",
        "manufacturer": "Copeland (Emerson)",
        "model": "CoreSense Diagnostics (Cloud)",
        "description": (
            "Copeland/Emerson CoreSense cloud integration for scroll compressors. "
            "Pulls diagnostic data via Copeland's connected services API. "
            "Common in supermarket and light commercial cold storage."
        ),
        "version": "1.0",
        "registers": {
            "protocol": "cloud_api",
            "api_base_url": "https://api.copeland.com/connected/v2",
            "auth_method": "api_key",
            "endpoints": {
                "list_devices": {"method": "GET", "path": "/devices"},
                "get_diagnostics": {"method": "GET", "path": "/devices/{device_id}/diagnostics"},
                "get_alerts": {"method": "GET", "path": "/devices/{device_id}/alerts"},
            },
            "field_mappings": {
                "suction_pressure": {"path": "diagnostics.suction_pressure", "unit": "psig"},
                "discharge_pressure": {"path": "diagnostics.discharge_pressure", "unit": "psig"},
                "discharge_temp": {"path": "diagnostics.discharge_temp", "unit": "degF"},
                "suction_temp": {"path": "diagnostics.suction_temp", "unit": "degF"},
                "current_draw": {"path": "diagnostics.current", "unit": "A"},
                "superheat": {"path": "diagnostics.superheat", "unit": "degF"},
                "subcooling": {"path": "diagnostics.subcooling", "unit": "degF"},
                "compressor_status": {"path": "diagnostics.state"},
            },
        },
    },
]


async def seed_register_maps(db):
    """
    Seed predefined register maps into the database.
    Skips maps that already exist (by name).
    """
    from app.models.integration import RegisterMap
    from sqlalchemy import select

    for seed in REGISTER_MAP_SEEDS:
        result = await db.execute(
            select(RegisterMap).where(RegisterMap.name == seed["name"])
        )
        existing = result.scalar_one_or_none()
        if existing:
            continue

        reg_map = RegisterMap(
            name=seed["name"],
            protocol=seed["protocol"],
            manufacturer=seed["manufacturer"],
            model=seed.get("model"),
            description=seed.get("description"),
            version=seed.get("version", "1.0"),
            registers=seed["registers"],
        )
        db.add(reg_map)

    await db.commit()


DEVICE_PROFILE_SEEDS = [
    {
        "manufacturer": "Emerson",
        "model": "E2 BACnet",
        "display_name": "Emerson E2/E3 (BACnet/IP)",
        "description": "Emerson E2/E3 controller via BACnet/IP for rack systems and walk-in coolers.",
        "equipment_type": "compressor",
        "protocol": "bacnet_ip",
        "default_port": 47808,
        "bacnet_config": {
            "device_instance": 1,
            "objects": {
                "suction_temp": {"type": "analog-input", "instance": 1},
                "suction_pressure": {"type": "analog-input", "instance": 2},
                "discharge_pressure": {"type": "analog-input", "instance": 3},
                "discharge_temp": {"type": "analog-input", "instance": 4},
                "compressor_running": {"type": "binary-input", "instance": 1},
            },
        },
    },
    {
        "manufacturer": "Danfoss",
        "model": "AK-PC 783A BACnet",
        "display_name": "Danfoss AK-PC 783A (BACnet/IP)",
        "description": "Danfoss pack controller for industrial refrigeration via BACnet/IP.",
        "equipment_type": "compressor",
        "protocol": "bacnet_ip",
        "default_port": 47808,
        "bacnet_config": {
            "device_instance": 1,
            "objects": {
                "suction_pressure": {"type": "analog-input", "instance": 1},
                "discharge_pressure": {"type": "analog-input", "instance": 2},
                "power_consumption": {"type": "analog-input", "instance": 10},
                "capacity_pct": {"type": "analog-input", "instance": 11},
                "pack_running": {"type": "binary-input", "instance": 1},
            },
        },
    },
    {
        "manufacturer": "Bitzer",
        "model": "BEST Cloud",
        "display_name": "Bitzer BEST (Cloud-to-Cloud)",
        "description": "Cloud integration with Bitzer Digital Network. Pulls compressor data via REST API.",
        "equipment_type": "compressor",
        "protocol": "cloud_api",
        "default_port": 443,
    },
    {
        "manufacturer": "Copeland (Emerson)",
        "model": "CoreSense Cloud",
        "display_name": "Copeland CoreSense Diagnostics (Cloud)",
        "description": "Cloud integration with Copeland connected services for scroll compressor diagnostics.",
        "equipment_type": "compressor",
        "protocol": "cloud_api",
        "default_port": 443,
    },
    {
        "manufacturer": "Johnson Controls / Frick",
        "model": "Quantum HD",
        "display_name": "Frick Quantum HD (Modbus TCP)",
        "description": (
            "Frick Quantum HD controller for industrial ammonia screw compressors "
            "(RWF, TDSH, RXF series). The dominant controller in North American "
            "ammonia cold storage engine rooms."
        ),
        "equipment_type": "compressor",
        "protocol": "modbus_tcp",
        "default_port": 502,
        "register_map": {
            "map_name": "frick_quantum_hd",
            "unit_id": 1,
            "key_registers": {
                "suction_pressure": 40301,
                "discharge_pressure": 40302,
                "oil_pressure": 40303,
                "suction_temp": 40310,
                "discharge_temp": 40311,
                "motor_amps": 40320,
                "motor_kw": 40321,
                "slide_valve_position": 40330,
                "run_hours": 40340,
                "compressor_status": 40350,
                "active_fault_code": 40351,
            },
        },
    },
    {
        "manufacturer": "GEA",
        "model": "Omni",
        "display_name": "GEA Omni — Grasso SP / GEA Bock (Modbus TCP)",
        "description": (
            "GEA Omni controller for Grasso SP and GEA Bock industrial screw "
            "compressors. Current-generation platform used in large ammonia and "
            "CO2 refrigeration installations."
        ),
        "equipment_type": "compressor",
        "protocol": "modbus_tcp",
        "default_port": 502,
        "register_map": {
            "map_name": "gea_omni",
            "unit_id": 1,
            "key_registers": {
                "suction_pressure": 40501,
                "discharge_pressure": 40502,
                "oil_pressure": 40503,
                "suction_temp": 40510,
                "discharge_temp": 40511,
                "motor_current": 40520,
                "motor_power": 40521,
                "slide_valve_position": 40530,
                "run_hours": 40540,
                "compressor_status": 40550,
                "fault_code": 40551,
            },
        },
    },
]


async def seed_device_profiles(db):
    """Seed built-in device profiles for BACnet and cloud integrations."""
    from app.models.device_profile import DeviceProfile
    from sqlalchemy import select

    for seed in DEVICE_PROFILE_SEEDS:
        result = await db.execute(
            select(DeviceProfile).where(
                DeviceProfile.manufacturer == seed["manufacturer"],
                DeviceProfile.model == seed["model"],
            )
        )
        if result.scalar_one_or_none():
            continue

        profile = DeviceProfile(
            manufacturer=seed["manufacturer"],
            model=seed["model"],
            display_name=seed["display_name"],
            description=seed.get("description"),
            equipment_type=seed.get("equipment_type", "compressor"),
            protocol=seed.get("protocol", "modbus_tcp"),
            default_port=seed.get("default_port", 502),
            register_map=seed.get("register_map", {}),
            bacnet_config=seed.get("bacnet_config"),
            is_builtin=True,
        )
        db.add(profile)

    await db.commit()
