"""
Alert & Event models — the alarm management system.

Alerts are generated by:
  - Edge agent detecting threshold breaches
  - Automation rules triggering conditions
  - Equipment health score degradation
  - Manual operator actions

Events are the immutable audit log of everything that happens.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    String, Integer, Boolean, DateTime, ForeignKey, Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.core.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    facility_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("facilities.id"), nullable=False
    )
    # Source
    zone_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("zones.id"), nullable=True
    )
    equipment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("equipment.id"), nullable=True
    )
    agent_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("edge_agents.id"), nullable=True
    )
    # Classification
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # critical, high, medium, low, info
    category: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # temperature, pressure, equipment, power, security, compliance
    alert_type: Mapped[str] = mapped_column(
        String(100), nullable=False
    )  # temp_high, temp_low, compressor_fault, door_open_extended, demand_spike, etc.
    # Content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=True)
    # State
    state: Mapped[str] = mapped_column(
        String(20), default="active"
    )  # active, acknowledged, resolved, suppressed
    acknowledged_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    acknowledged_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    resolution_note: Mapped[str] = mapped_column(Text, nullable=True)
    # Trigger data
    trigger_value: Mapped[float] = mapped_column(nullable=True)  # the value that triggered it
    threshold_value: Mapped[float] = mapped_column(nullable=True)  # the threshold that was breached
    context: Mapped[dict] = mapped_column(JSONB, nullable=True, default=dict)
    # Timestamps
    triggered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    def __repr__(self):
        return f"<Alert [{self.severity}] {self.alert_type}: {self.title}>"


class Event(Base):
    """Immutable audit log of all system events."""
    __tablename__ = "events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    facility_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("facilities.id"), nullable=False
    )
    # Source
    event_type: Mapped[str] = mapped_column(
        String(100), nullable=False
    )  # equipment.started, zone.temp_breach, agent.connected, control.setpoint_changed, etc.
    source: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # agent, user, automation, system
    # References
    zone_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("zones.id"), nullable=True
    )
    equipment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("equipment.id"), nullable=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    alert_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("alerts.id"), nullable=True
    )
    # Content
    description: Mapped[str] = mapped_column(Text, nullable=False)
    data: Mapped[dict] = mapped_column(JSONB, nullable=True, default=dict)
    # Timestamp
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    def __repr__(self):
        return f"<Event {self.event_type} @ {self.occurred_at}>"


# Forward references
from app.models.facility import Facility, Equipment  # noqa: E402, F401
from app.models.zone import Zone  # noqa: E402, F401
from app.models.agent import EdgeAgent  # noqa: E402, F401
from app.models.user import User  # noqa: E402, F401
