// Package config handles YAML configuration loading for the edge agent.
//
// The config file is generated by Kelvex's platform UI and dropped onto
// the gateway device at /etc/kelvex/agent.yaml.
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Agent    AgentConfig    `yaml:"agent"`
	Platform PlatformConfig `yaml:"platform"`
	Devices  []DeviceConfig `yaml:"devices"`
	Local    LocalConfig    `yaml:"local"`
}

type AgentConfig struct {
	Name string `yaml:"name"`
	Key  string `yaml:"key"`
}

type PlatformConfig struct {
	URL                 string `yaml:"url"`
	HeartbeatIntervalSec int   `yaml:"heartbeat_interval_sec"`
	// If true, agent can operate in offline-only mode with local UI
	AllowOffline bool `yaml:"allow_offline"`
}

type DeviceConfig struct {
	Name           string              `yaml:"name"`
	Host           string              `yaml:"host"`
	Port           int                 `yaml:"port"`
	SlaveID        int                 `yaml:"slave_id"`
	Protocol       string              `yaml:"protocol"`
	PollIntervalSec int               `yaml:"poll_interval_sec"`
	CompressorID   string              `yaml:"compressor_id"`
	Registers      map[string]Register `yaml:"registers"`
	// Write-enabled registers for control
	WriteRegisters map[string]Register `yaml:"write_registers"`
}

type Register struct {
	Address  uint16  `yaml:"register"`
	Type     string  `yaml:"type"`      // holding, input, coil
	DataType string  `yaml:"data_type"` // uint16, int16, float32, bool
	Scale    float64 `yaml:"scale"`
	Offset   float64 `yaml:"offset"`
	Unit     string  `yaml:"unit"`
	Desc     string  `yaml:"description"`
}

type LocalConfig struct {
	// Local web dashboard
	WebPort      int    `yaml:"web_port"`       // default 8080
	WebEnabled   bool   `yaml:"web_enabled"`    // default true
	// Local data buffer
	BufferPath   string `yaml:"buffer_path"`    // default /var/lib/kelvex/buffer.db
	BufferMaxMB  int    `yaml:"buffer_max_mb"`  // default 500
	// Network scanning
	ScanSubnet   string `yaml:"scan_subnet"`    // e.g. "192.168.1.0/24", auto-detect if empty
}

func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}

	cfg := &Config{
		Platform: PlatformConfig{
			HeartbeatIntervalSec: 30,
		},
		Local: LocalConfig{
			WebPort:     8080,
			WebEnabled:  true,
			BufferPath:  "/var/lib/kelvex/buffer.db",
			BufferMaxMB: 500,
		},
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	// Defaults
	for i := range cfg.Devices {
		if cfg.Devices[i].Port == 0 {
			cfg.Devices[i].Port = 502
		}
		if cfg.Devices[i].SlaveID == 0 {
			cfg.Devices[i].SlaveID = 1
		}
		if cfg.Devices[i].PollIntervalSec == 0 {
			cfg.Devices[i].PollIntervalSec = 15
		}
		if cfg.Devices[i].Protocol == "" {
			cfg.Devices[i].Protocol = "modbus_tcp"
		}
	}

	return cfg, nil
}

// LoadOrBootstrap loads config from file, or creates a bootstrap config
// that enables the local web UI for first-time setup.
func LoadOrBootstrap(path string) (*Config, bool, error) {
	cfg, err := Load(path)
	if err == nil {
		return cfg, false, nil
	}

	// Bootstrap mode — no config file, start with just the local web UI
	// so the tech can configure via browser
	bootstrap := &Config{
		Agent: AgentConfig{Name: "unconfigured"},
		Local: LocalConfig{
			WebPort:    8080,
			WebEnabled: true,
			BufferPath: "/var/lib/kelvex/buffer.db",
		},
	}
	return bootstrap, true, nil
}
