// Package config handles YAML configuration loading for the edge agent.
//
// The config file is generated by Kelvex's platform UI and dropped onto
// the gateway device at /etc/kelvex/agent.yaml.
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Agent        AgentConfig        `yaml:"agent"`
	Platform     PlatformConfig     `yaml:"platform"`
	Devices      []DeviceConfig     `yaml:"devices"`
	ZoneSensors  []ZoneSensorConfig `yaml:"zone_sensors"`
	Integrations IntegrationConfig  `yaml:"integrations"`
	Local        LocalConfig        `yaml:"local"`
}

// IntegrationConfig holds optional plug-and-play integrations.
// These run alongside the Modbus poll loop and push data via the same
// /agents/{key}/zone-readings endpoint the zone sensor loop uses.
type IntegrationConfig struct {
	DanfossAKSM []AKSMConfig `yaml:"danfoss_aksm"`
	MQTT        []MQTTConfig `yaml:"mqtt"`
}

// AKSMConfig configures a Danfoss AK-SM 800 / AK-SM 800A local XML integration.
// The AK-SM exposes all connected case controller temperatures over its built-in
// HTTP XML interface — no Alsense cloud subscription or partner API needed.
type AKSMConfig struct {
	Host            string            `yaml:"host"`
	Username        string            `yaml:"username"`
	Password        string            `yaml:"password"`
	PollIntervalSec int               `yaml:"poll_interval_sec"`
	// ZoneMappings links AK-SM device IDs to Kelvex zone/sensor UUIDs.
	// If empty the integration still polls — readings appear under
	// sensor_id="" and the platform can map them later.
	ZoneMappings []AKSMZoneMapping `yaml:"zone_mappings"`
}

type AKSMZoneMapping struct {
	ControllerID string `yaml:"controller_id"` // e.g. "CC01" or the controller name
	ZoneID       string `yaml:"zone_id"`
	SensorID     string `yaml:"sensor_id"`
	// TempPoint is the Danfoss parameter to use as the zone temperature.
	// Common values: S2 (air-off/return air), S1 (suction), S3 (air-on).
	// Defaults to S2.
	TempPoint string `yaml:"temp_point"`
}

// MQTTConfig subscribes to one MQTT broker and routes incoming JSON payloads
// to zone sensor readings. Works with Chirpstack, Monnit, ControlByWeb, and
// any broker that publishes JSON temperature data.
type MQTTConfig struct {
	Broker   string             `yaml:"broker"`    // e.g. "tcp://192.168.1.50:1883"
	ClientID string             `yaml:"client_id"` // defaults to "kelvex-agent"
	Username string             `yaml:"username"`
	Password string             `yaml:"password"`
	Sensors  []MQTTSensorConfig `yaml:"sensors"`
}

type MQTTSensorConfig struct {
	Topic    string `yaml:"topic"`     // e.g. "sensors/zone1/temp"
	SensorID string `yaml:"sensor_id"` // Kelvex ZoneSensor UUID
	ZoneID   string `yaml:"zone_id"`   // Kelvex Zone UUID
	// ValueKey is a dot-notation path into the JSON payload.
	// Examples: "temperature", "object.TempC_DS18B20", "data.value"
	ValueKey string `yaml:"value_key"`
	Unit     string `yaml:"unit"` // "F" or "C"
}

type AgentConfig struct {
	Name string `yaml:"name"`
	Key  string `yaml:"key"`
}

type PlatformConfig struct {
	URL                 string `yaml:"url"`
	HeartbeatIntervalSec int   `yaml:"heartbeat_interval_sec"`
	// If true, agent can operate in offline-only mode with local UI
	AllowOffline bool `yaml:"allow_offline"`
}

type DeviceConfig struct {
	Name           string              `yaml:"name"`
	Host           string              `yaml:"host"`
	Port           int                 `yaml:"port"`
	SlaveID        int                 `yaml:"slave_id"`
	Protocol       string              `yaml:"protocol"`
	PollIntervalSec int               `yaml:"poll_interval_sec"`
	CompressorID   string              `yaml:"compressor_id"`
	Registers      map[string]Register `yaml:"registers"`
	// Write-enabled registers for control
	WriteRegisters map[string]Register `yaml:"write_registers"`
}

type Register struct {
	Address  uint16  `yaml:"register"`
	Type     string  `yaml:"type"`      // holding, input, coil
	DataType string  `yaml:"data_type"` // uint16, int16, float32, bool
	Scale    float64 `yaml:"scale"`
	Offset   float64 `yaml:"offset"`
	Unit     string  `yaml:"unit"`
	Desc     string  `yaml:"description"`
}

// ZoneSensorConfig describes a single Modbus-polled zone sensor (temp probe, humidity, door contact, etc.).
type ZoneSensorConfig struct {
	SensorID        string  `yaml:"sensor_id"`
	ZoneID          string  `yaml:"zone_id"`
	Name            string  `yaml:"name"`
	SensorType      string  `yaml:"sensor_type"`   // temperature, humidity, door_contact, etc.
	Unit            string  `yaml:"unit"`
	Host            string  `yaml:"host"`
	Port            int     `yaml:"port"`
	SlaveID         int     `yaml:"slave_id"`
	RegisterAddress uint16  `yaml:"register_address"`
	RegisterType    string  `yaml:"register_type"`  // holding or input
	DataType        string  `yaml:"data_type"`       // uint16, int16, float32, int32
	Scale           float64 `yaml:"scale"`
	Offset          float64 `yaml:"offset"`
	PollIntervalSec int     `yaml:"poll_interval_sec"`
}

type LocalConfig struct {
	// Local web dashboard
	WebPort      int    `yaml:"web_port"`       // default 8080
	WebEnabled   bool   `yaml:"web_enabled"`    // default true
	// Local data buffer
	BufferPath   string `yaml:"buffer_path"`    // default /var/lib/kelvex/buffer.db
	BufferMaxMB  int    `yaml:"buffer_max_mb"`  // default 500
	// Network scanning
	ScanSubnet   string `yaml:"scan_subnet"`    // e.g. "192.168.1.0/24", auto-detect if empty
}

func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}

	cfg := &Config{
		Platform: PlatformConfig{
			HeartbeatIntervalSec: 30,
		},
		Local: LocalConfig{
			WebPort:     8080,
			WebEnabled:  true,
			BufferPath:  "/var/lib/kelvex/buffer.db",
			BufferMaxMB: 500,
		},
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	// Defaults for compressor devices
	for i := range cfg.Devices {
		if cfg.Devices[i].Port == 0 {
			cfg.Devices[i].Port = 502
		}
		if cfg.Devices[i].SlaveID == 0 {
			cfg.Devices[i].SlaveID = 1
		}
		if cfg.Devices[i].PollIntervalSec == 0 {
			cfg.Devices[i].PollIntervalSec = 15
		}
		if cfg.Devices[i].Protocol == "" {
			cfg.Devices[i].Protocol = "modbus_tcp"
		}
	}

	// Defaults for AK-SM integrations
	for i := range cfg.Integrations.DanfossAKSM {
		if cfg.Integrations.DanfossAKSM[i].PollIntervalSec == 0 {
			cfg.Integrations.DanfossAKSM[i].PollIntervalSec = 60
		}
		for j := range cfg.Integrations.DanfossAKSM[i].ZoneMappings {
			if cfg.Integrations.DanfossAKSM[i].ZoneMappings[j].TempPoint == "" {
				cfg.Integrations.DanfossAKSM[i].ZoneMappings[j].TempPoint = "S2"
			}
		}
	}

	// Defaults for MQTT integrations
	for i := range cfg.Integrations.MQTT {
		if cfg.Integrations.MQTT[i].ClientID == "" {
			cfg.Integrations.MQTT[i].ClientID = "kelvex-agent"
		}
	}

	// Defaults for zone sensors
	for i := range cfg.ZoneSensors {
		if cfg.ZoneSensors[i].Port == 0 {
			cfg.ZoneSensors[i].Port = 502
		}
		if cfg.ZoneSensors[i].SlaveID == 0 {
			cfg.ZoneSensors[i].SlaveID = 1
		}
		if cfg.ZoneSensors[i].PollIntervalSec == 0 {
			cfg.ZoneSensors[i].PollIntervalSec = 30
		}
		if cfg.ZoneSensors[i].Scale == 0 {
			cfg.ZoneSensors[i].Scale = 1.0
		}
		if cfg.ZoneSensors[i].RegisterType == "" {
			cfg.ZoneSensors[i].RegisterType = "holding"
		}
		if cfg.ZoneSensors[i].DataType == "" {
			cfg.ZoneSensors[i].DataType = "uint16"
		}
	}

	return cfg, nil
}

// LoadOrBootstrap loads config from file, or creates a bootstrap config
// that enables the local web UI for first-time setup.
func LoadOrBootstrap(path string) (*Config, bool, error) {
	cfg, err := Load(path)
	if err == nil {
		return cfg, false, nil
	}

	// Bootstrap mode — no config file, start with just the local web UI
	// so the tech can configure via browser
	bootstrap := &Config{
		Agent: AgentConfig{Name: "unconfigured"},
		Local: LocalConfig{
			WebPort:    8080,
			WebEnabled: true,
			BufferPath: "/var/lib/kelvex/buffer.db",
		},
	}
	return bootstrap, true, nil
}
