"""add_org_features_table

Revision ID: 0f5b44a26446
Revises: e15532532200
Create Date: 2026-05-08 15:18:06.717110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f5b44a26446'
down_revision: Union[str, None] = 'e15532532200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'feature_key', name='uq_org_feature_key')
    )
    op.create_index('ix_org_features_org_id', 'org_features', ['org_id'], unique=False)
    op.create_table('circuit_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('circuit_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('projected_adds_lbs', sa.Float(), nullable=True),
    sa.Column('projected_adds_lbs_low', sa.Float(), nullable=True),
    sa.Column('projected_adds_lbs_high', sa.Float(), nullable=True),
    sa.Column('lbs_per_day', sa.Float(), nullable=True),
    sa.Column('days_to_aim_threshold', sa.Integer(), nullable=True),
    sa.Column('days_to_aim_warning', sa.Integer(), nullable=True),
    sa.Column('current_annual_leak_rate_pct', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['refrigerant_circuits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_id')
    )
    op.create_index('ix_circuit_forecasts_org_id', 'circuit_forecasts', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_circuit_forecasts_org_id', table_name='circuit_forecasts')
    op.drop_table('circuit_forecasts')
    op.drop_index('ix_org_features_org_id', table_name='org_features')
    op.drop_table('org_features')
    # ### end Alembic commands ###
