"""link_refrigerant_circuit_to_compressor_rack

Revision ID: e15532532200
Revises: f2a803cbacae
Create Date: 2026-05-07 19:21:17.325731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15532532200'
down_revision: Union[str, None] = 'f2a803cbacae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refrigerant_circuits', sa.Column('rack_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'refrigerant_circuits', 'compressor_racks', ['rack_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refrigerant_circuits', type_='foreignkey')
    op.drop_column('refrigerant_circuits', 'rack_id')
    # ### end Alembic commands ###
