"""add refrigerant tracking tables

Revision ID: f2a803cbacae
Revises: 012
Create Date: 2026-05-07 16:38:51.480011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2a803cbacae'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refrigerant_circuits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('refrigerant_type', sa.String(length=50), nullable=False),
    sa.Column('full_charge_lbs', sa.Float(), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refrigerant_circuit_facility', 'refrigerant_circuits', ['facility_id'], unique=False)
    op.create_table('leak_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('circuit_id', sa.UUID(), nullable=True),
    sa.Column('rack_name', sa.String(length=255), nullable=False),
    sa.Column('zone_name', sa.String(length=255), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repaired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_loss_lbs', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['refrigerant_circuits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leak_event_circuit', 'leak_events', ['circuit_id'], unique=False)
    op.create_index('ix_leak_event_facility_detected', 'leak_events', ['facility_id', 'detected_at'], unique=False)
    op.create_table('refrigerant_adds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('circuit_id', sa.UUID(), nullable=True),
    sa.Column('leak_event_id', sa.UUID(), nullable=True),
    sa.Column('rack_name', sa.String(length=255), nullable=False),
    sa.Column('refrigerant_type', sa.String(length=50), nullable=False),
    sa.Column('amount_lbs', sa.Float(), nullable=False),
    sa.Column('cost_per_lb', sa.Float(), nullable=True),
    sa.Column('technician_name', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['refrigerant_circuits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leak_event_id'], ['leak_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refrigerant_add_facility_added', 'refrigerant_adds', ['facility_id', 'added_at'], unique=False)
    op.create_index('ix_refrigerant_add_leak_event', 'refrigerant_adds', ['leak_event_id'], unique=False)
    op.create_table('repair_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('circuit_id', sa.UUID(), nullable=True),
    sa.Column('leak_event_id', sa.UUID(), nullable=True),
    sa.Column('rack_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technician_name', sa.String(length=255), nullable=False),
    sa.Column('technician_company', sa.String(length=255), nullable=True),
    sa.Column('repaired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parts_replaced', sa.String(length=500), nullable=True),
    sa.Column('verified_leak_free', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('refrigerant_recovered_lbs', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['refrigerant_circuits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leak_event_id'], ['leak_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repair_record_facility_repaired', 'repair_records', ['facility_id', 'repaired_at'], unique=False)
    op.create_index('ix_repair_record_leak_event', 'repair_records', ['leak_event_id'], unique=False)
    op.alter_column('agent_devices', 'port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('502'))
    op.alter_column('agent_devices', 'slave_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_devices', 'poll_interval_sec',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('agent_devices', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_devices', 'connection_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''unknown'''::character varying"))
    op.alter_column('agent_devices', 'poll_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_devices', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_agent_devices_compressor_id', table_name='agent_devices')
    op.alter_column('agent_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_agent_logs_agent_time', table_name='agent_logs')
    op.alter_column('alerts', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('alerts', 'trigger_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('alerts', 'threshold_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('alerts', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_alerts_facility_state', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.alter_column('automation_rules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('automation_rules', 'cooldown_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('automation_rules', 'max_executions_per_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('automation_rules', 'execution_count_today',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('automation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_automation_rules_facility', table_name='automation_rules')
    op.alter_column('command_queue', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('command_queue', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('command_queue', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_cmd_queue_agent_state', table_name='command_queue')
    op.drop_index('idx_cmd_queue_facility', table_name='command_queue')
    op.alter_column('compliance_logs', 'temp_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'degF'::character varying"))
    op.alter_column('compliance_logs', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('compliance_reports', 'total_checks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'passed_checks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'failed_checks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'excursion_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'compliance_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'100'::double precision"))
    op.alter_column('compliance_reports', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('compliance_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compressor_racks', 'staging_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('compressor_racks', 'demand_response_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('compressor_racks', 'min_capacity_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'25'::double precision"))
    op.alter_column('compressor_racks', 'max_coast_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('compressor_racks', 'thermal_mass_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('compressor_racks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_racks_facility', table_name='compressor_racks')
    op.alter_column('compressor_readings', 'alarm_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('compressors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compressors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('compressors', 'staging_priority')
    op.drop_column('compressors', 'defrost_config')
    op.drop_column('compressors', 'efficiency_kw_per_ton')
    op.drop_column('compressors', 'rack_id')
    op.alter_column('control_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_control_audit_facility', table_name='control_audit_log')
    op.alter_column('control_sequences', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('control_sequences', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('control_sequences', 'run_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('control_sequences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_sequences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_control_seq_facility', table_name='control_sequences')
    op.alter_column('critical_control_points', 'metric_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'temperature'::character varying"))
    op.alter_column('critical_control_points', 'temp_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'degF'::character varying"))
    op.alter_column('critical_control_points', 'warning_offset',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'2'::double precision"))
    op.alter_column('critical_control_points', 'check_interval_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('critical_control_points', 'excursion_threshold_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('critical_control_points', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('critical_control_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('demand_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_profiles', 'refrigerant_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('device_profiles', 'default_port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('502'))
    op.alter_column('device_profiles', 'default_slave_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('device_profiles', 'is_builtin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('device_profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('device_profiles', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('device_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_device_profiles_manufacturer', table_name='device_profiles')
    op.alter_column('edge_agents', 'connection_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.alter_column('edge_agents', 'heartbeat_interval_sec',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('edge_agents', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('edge_agents', 'config_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('edge_agents', 'pending_commands',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('edge_agents', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_edge_agents_facility', table_name='edge_agents')
    op.alter_column('equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalation_events', 'notified_targets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('escalation_events', 'escalated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalation_policies', 'min_severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'high'::character varying"))
    op.alter_column('escalation_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('escalation_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_events_facility_time', table_name='events')
    op.drop_index('idx_events_type', table_name='events')
    op.alter_column('facilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_intcred_facility', table_name='integration_credentials')
    op.drop_index('ix_intcred_provider', table_name='integration_credentials')
    op.alter_column('integrations', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('integrations', 'connection_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.alter_column('integrations', 'total_polls',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('integrations', 'total_errors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('integrations', 'total_readings_ingested',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_integration_enabled', table_name='integrations')
    op.drop_index('ix_integration_facility', table_name='integrations')
    op.drop_index('ix_integration_provider', table_name='integrations')
    op.drop_index('ix_integration_state', table_name='integrations')
    op.alter_column('maintenance_tasks', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'preventive'::character varying"))
    op.alter_column('maintenance_tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('maintenance_tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('maintenance_tasks', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('maintenance_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_channels', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('notification_channels', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notif_channel_org', table_name='notification_channels')
    op.alter_column('notification_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('notification_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notif_log_org', table_name='notification_logs')
    op.drop_index('ix_notif_log_sent_at', table_name='notification_logs')
    op.alter_column('organizations', 'plan_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rate_schedules', 'sector',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'commercial'::character varying"))
    op.alter_column('rate_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('register_maps', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('register_maps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_regmap_manufacturer', table_name='register_maps')
    op.drop_index('ix_regmap_protocol', table_name='register_maps')
    op.alter_column('savings_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schedules', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'America/Chicago'::character varying"))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('telemetry', 'quality',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.drop_index('idx_telemetry_equip_metric_time', table_name='telemetry')
    op.drop_index('telemetry_time_idx', table_name='telemetry')
    op.alter_column('temp_excursions', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('temp_excursions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_facility_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_ufa_facility', table_name='user_facility_access')
    op.drop_index('ix_ufa_user', table_name='user_facility_access')
    op.create_index(op.f('ix_user_facility_access_facility_id'), 'user_facility_access', ['facility_id'], unique=False)
    op.create_index(op.f('ix_user_facility_access_user_id'), 'user_facility_access', ['user_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('utilities', 'regulated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('utilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('utility_bills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('zone_equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_zone_equip_equip', table_name='zone_equipment')
    op.drop_index('idx_zone_equip_zone', table_name='zone_equipment')
    op.alter_column('zone_readings', 'quality',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('zone_sensors', 'current_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('zone_sensors', 'poll_interval_sec',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('zone_sensors', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('zone_sensors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_zone_sensors_zone', table_name='zone_sensors')
    op.alter_column('zones', 'temp_unit',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'F'::character varying"))
    op.alter_column('zones', 'temp_tolerance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'2'::double precision"))
    op.alter_column('zones', 'door_open',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('zones', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('zones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_zones_facility', table_name='zones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_zones_facility', 'zones', ['facility_id'], unique=False)
    op.alter_column('zones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('zones', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('zones', 'door_open',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('zones', 'temp_tolerance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'2'::double precision"))
    op.alter_column('zones', 'temp_unit',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'F'::character varying"))
    op.create_index('ix_zone_sensors_zone', 'zone_sensors', ['zone_id'], unique=False)
    op.alter_column('zone_sensors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('zone_sensors', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('zone_sensors', 'poll_interval_sec',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('zone_sensors', 'current_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('zone_readings', 'quality',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_zone_equip_zone', 'zone_equipment', ['zone_id'], unique=False)
    op.create_index('idx_zone_equip_equip', 'zone_equipment', ['equipment_id'], unique=False)
    op.alter_column('zone_equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('utility_bills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('utilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('utilities', 'regulated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_user_facility_access_user_id'), table_name='user_facility_access')
    op.drop_index(op.f('ix_user_facility_access_facility_id'), table_name='user_facility_access')
    op.create_index('ix_ufa_user', 'user_facility_access', ['user_id'], unique=False)
    op.create_index('ix_ufa_facility', 'user_facility_access', ['facility_id'], unique=False)
    op.alter_column('user_facility_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('temp_excursions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('temp_excursions', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index('telemetry_time_idx', 'telemetry', [sa.text('time DESC')], unique=False)
    op.create_index('idx_telemetry_equip_metric_time', 'telemetry', ['equipment_id', 'metric_name', sa.text('time DESC')], unique=False)
    op.alter_column('telemetry', 'quality',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'America/Chicago'::character varying"))
    op.alter_column('schedules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('savings_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_regmap_protocol', 'register_maps', ['protocol'], unique=False)
    op.create_index('ix_regmap_manufacturer', 'register_maps', ['manufacturer'], unique=False)
    op.alter_column('register_maps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('register_maps', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('rate_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rate_schedules', 'sector',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'commercial'::character varying"))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'plan_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.create_index('ix_notif_log_sent_at', 'notification_logs', ['sent_at'], unique=False)
    op.create_index('ix_notif_log_org', 'notification_logs', ['org_id'], unique=False)
    op.alter_column('notification_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'sent'::character varying"))
    op.create_index('ix_notif_channel_org', 'notification_channels', ['org_id'], unique=False)
    op.alter_column('notification_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_channels', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_channels', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('maintenance_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('maintenance_tasks', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('maintenance_tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('maintenance_tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('maintenance_tasks', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'preventive'::character varying"))
    op.create_index('ix_integration_state', 'integrations', ['connection_state'], unique=False)
    op.create_index('ix_integration_provider', 'integrations', ['provider'], unique=False)
    op.create_index('ix_integration_facility', 'integrations', ['facility_id'], unique=False)
    op.create_index('ix_integration_enabled', 'integrations', ['enabled'], unique=False)
    op.alter_column('integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'total_readings_ingested',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('integrations', 'total_errors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('integrations', 'total_polls',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('integrations', 'connection_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.alter_column('integrations', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('ix_intcred_provider', 'integration_credentials', ['provider'], unique=False)
    op.create_index('ix_intcred_facility', 'integration_credentials', ['facility_id'], unique=False)
    op.alter_column('integration_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('facilities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_events_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_facility_time', 'events', ['facility_id', 'occurred_at'], unique=False)
    op.alter_column('events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalation_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalation_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('escalation_policies', 'min_severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'high'::character varying"))
    op.alter_column('escalation_events', 'escalated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalation_events', 'notified_targets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_edge_agents_facility', 'edge_agents', ['facility_id'], unique=False)
    op.alter_column('edge_agents', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('edge_agents', 'pending_commands',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('edge_agents', 'config_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('edge_agents', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('edge_agents', 'heartbeat_interval_sec',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('edge_agents', 'connection_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'disconnected'::character varying"))
    op.create_index('ix_device_profiles_manufacturer', 'device_profiles', ['manufacturer'], unique=False)
    op.alter_column('device_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_profiles', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('device_profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('device_profiles', 'is_builtin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('device_profiles', 'default_slave_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('device_profiles', 'default_port',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('502'))
    op.alter_column('device_profiles', 'refrigerant_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('demand_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('critical_control_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('critical_control_points', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('critical_control_points', 'excursion_threshold_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('critical_control_points', 'check_interval_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.alter_column('critical_control_points', 'warning_offset',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'2'::double precision"))
    op.alter_column('critical_control_points', 'temp_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'degF'::character varying"))
    op.alter_column('critical_control_points', 'metric_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'temperature'::character varying"))
    op.create_index('idx_control_seq_facility', 'control_sequences', ['facility_id'], unique=False)
    op.alter_column('control_sequences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_sequences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('control_sequences', 'run_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('control_sequences', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('control_sequences', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('ix_control_audit_facility', 'control_audit_log', ['facility_id', 'created_at'], unique=False)
    op.alter_column('control_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('compressors', sa.Column('rack_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('compressors', sa.Column('efficiency_kw_per_ton', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('compressors', sa.Column('defrost_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('compressors', sa.Column('staging_priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('compressors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compressors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compressor_readings', 'alarm_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_racks_facility', 'compressor_racks', ['facility_id'], unique=False)
    op.alter_column('compressor_racks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compressor_racks', 'thermal_mass_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('compressor_racks', 'max_coast_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('compressor_racks', 'min_capacity_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'25'::double precision"))
    op.alter_column('compressor_racks', 'demand_response_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('compressor_racks', 'staging_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('compliance_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compliance_reports', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('compliance_reports', 'compliance_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'100'::double precision"))
    op.alter_column('compliance_reports', 'excursion_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'failed_checks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'passed_checks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_reports', 'total_checks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('compliance_logs', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('compliance_logs', 'temp_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'degF'::character varying"))
    op.create_index('idx_cmd_queue_facility', 'command_queue', ['facility_id'], unique=False)
    op.create_index('idx_cmd_queue_agent_state', 'command_queue', ['agent_id', 'state'], unique=False)
    op.alter_column('command_queue', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('command_queue', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('command_queue', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index('idx_automation_rules_facility', 'automation_rules', ['facility_id'], unique=False)
    op.alter_column('automation_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('automation_rules', 'execution_count_today',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('automation_rules', 'max_executions_per_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('automation_rules', 'cooldown_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('automation_rules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('idx_alerts_severity', 'alerts', ['severity', 'triggered_at'], unique=False)
    op.create_index('idx_alerts_facility_state', 'alerts', ['facility_id', 'state'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'threshold_value',
               existing_type=sa.String(length=255),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('alerts', 'trigger_value',
               existing_type=sa.String(length=255),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('alerts', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index('idx_agent_logs_agent_time', 'agent_logs', ['agent_id', 'logged_at'], unique=False)
    op.alter_column('agent_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_agent_devices_compressor_id', 'agent_devices', ['compressor_id'], unique=False)
    op.alter_column('agent_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_devices', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_devices', 'poll_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_devices', 'connection_state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''unknown'''::character varying"))
    op.alter_column('agent_devices', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_devices', 'poll_interval_sec',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.alter_column('agent_devices', 'slave_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_devices', 'port',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('502'))
    op.drop_index('ix_repair_record_leak_event', table_name='repair_records')
    op.drop_index('ix_repair_record_facility_repaired', table_name='repair_records')
    op.drop_table('repair_records')
    op.drop_index('ix_refrigerant_add_leak_event', table_name='refrigerant_adds')
    op.drop_index('ix_refrigerant_add_facility_added', table_name='refrigerant_adds')
    op.drop_table('refrigerant_adds')
    op.drop_index('ix_leak_event_facility_detected', table_name='leak_events')
    op.drop_index('ix_leak_event_circuit', table_name='leak_events')
    op.drop_table('leak_events')
    op.drop_index('ix_refrigerant_circuit_facility', table_name='refrigerant_circuits')
    op.drop_table('refrigerant_circuits')
    # ### end Alembic commands ###
